// src/config/registry.lite.ts
import { ToolMetaLite } from "@/types/tool-search";

/**
 * LIGHTWEIGHT registry for the home page and search.
 * Excludes heavy TIP configurations and long descriptions to keep the
 * initial bundle size under Cloudflare's 3MB limit.
 */
export const TOOLS_LITE: ToolMetaLite[] = [
  {
    id: 'note-vault',
    name: 'Note Vault',
    description: 'Secure, offline-first markdown notes with local-only storage.',
    category: 'text',
    route: 'note-vault',
    thumbnail: '/assets/thumbnails/note-vault.png',
    tags: ['notes', 'markdown', 'offline', 'privacy', 'editor'],
    isNew: false,
    isFeatured: true,
    wasmPowered: false,
    status: 'stable',
    addedAt: '2025-01-01',
    mobileOptimized: true,
  },

  {
    id: 'magic-pdf',
    name: 'Magic PDF',
    description: 'Compress, merge, split, protect, sign and convert PDFs — all in your browser.',
    category: 'pdf',
    route: 'magic-pdf',
    thumbnail: '/assets/thumbnails/magic-pdf.png',
    tags: ['pdf', 'compress', 'merge', 'split', 'protect', 'sign', 'convert', 'word', 'image'],
    isNew: false,
    isFeatured: true,
    wasmPowered: true,
    pythonPowered: true,
    status: 'stable',
    addedAt: '2025-01-01',
    mobileOptimized: true,
  },
  {
    id: 'pixels',
    name: 'Pixels',
    description: 'Compress, resize, upscale images and hide messages with steganography.',
    category: 'image',
    route: 'pixels',
    thumbnail: '/assets/thumbnails/pixels.png',
    tags: ['image', 'compress', 'resize', 'upscale', 'steganography', 'png', 'jpg', 'webp'],
    isNew: false,
    isFeatured: true,
    wasmPowered: true,
    pythonPowered: true,
    status: 'stable',
    addedAt: '2025-01-01',
    mobileOptimized: true,
  },
  {
    id: 'data-lens',
    name: 'Data Lens',
    description: 'Analyze CSV and JSON data with SQL queries, Python scripts and charts.',
    category: 'data',
    route: 'data-lens',
    thumbnail: '/assets/thumbnails/data-lens.png',
    tags: ['csv', 'json', 'sql', 'python', 'pandas', 'chart', 'data', 'analysis', 'filter'],
    isNew: false,
    isFeatured: true,
    wasmPowered: true,
    pythonPowered: true,
    status: 'stable',
    addedAt: '2025-01-01',
    mobileOptimized: false,
  },
  {
    id: 'bgremover',
    name: 'BG Remover',
    description: 'Remove backgrounds from images instantly using local AI.',
    category: 'image',
    route: 'bgremover',
    thumbnail: '/assets/thumbnails/bgremover.png',
    tags: ['image', 'background', 'remove', 'ai', 'segmentation', 'transparent'],
    isNew: true,
    isFeatured: true,
    wasmPowered: true,
    status: 'stable',
    addedAt: '2025-05-10',
    mobileOptimized: true,
  },
  {
    id: 'redact-secrets',
    name: 'Redact Secrets',
    description: 'Automatically detect and redact API keys and sensitive data.',
    category: 'security',
    route: 'redact-secrets',
    thumbnail: '/assets/thumbnails/redact-secrets.png',
    tags: ['redact', 'secrets', 'security', 'privacy'],
    wasmPowered: true,
    status: 'stable',
    addedAt: '2025-01-01',
    mobileOptimized: true,
  },
  {
    id: 'base64',
    name: 'Base64 Tool',
    description: 'Encode and decode Base64 strings and files.',
    category: 'developer',
    route: 'base64',
    thumbnail: '/assets/thumbnails/base64.png',
    tags: ['base64', 'encode', 'decode'],
    status: 'stable',
    addedAt: '2025-01-01',
    mobileOptimized: true,
  },
  {
    id: 'open-draw',
    name: 'Open Draw',
    description: 'Virtual whiteboard for sketching and diagrams.',
    category: 'drawing',
    route: 'open-draw',
    thumbnail: '/assets/thumbnails/open-draw.png',
    tags: ['draw', 'sketch', 'diagram', 'whiteboard'],
    wasmPowered: true,
    status: 'stable',
    addedAt: '2025-01-01',
    mobileOptimized: true,
  },
  {
    id: 'pipeline',
    name: 'Pipeline Builder',
    description: 'Chain multiple tools together into an automated workflow.',
    category: 'text',
    route: 'pipeline',
    thumbnail: '/assets/thumbnails/pipeline.png',
    tags: ['pipeline', 'workflow', 'automation', 'chain'],
    status: 'beta',
    addedAt: '2025-02-01',
    mobileOptimized: false,
  }
];

