name: build-and-deploy

on:
  push:
    branches: [main]

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployement
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.INFRA_DISPATCH_PAT }}
          repository: openbuildnetwork/toolbase-infra
          event-type: deploy
          client-payload: |
            {"sha": "${{ github.sha }}", "ref": "${{ github.ref_name }}"}
